[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "tensor-mars"
version = "0.1.0"
description = "Never gonna give you up!"
readme = "README.md"
requires-python = ">=3.13"

dependencies = [
    "torch",
    "torchvision",
    "triton",
    "pandas",
    "numpy",
    "einops",
    "opt_einsum",
    "jaxtyping",
    "tqdm",
    "huggingface_hub",
    "safetensors",
    "datasets",
    "transformers",
    "tokenizers",
    "wandb",
    "numba>=0.61",
    "quimb",
    "kornia",
    "bidict",
    "scikit-learn",
    "matplotlib",
    "plotly",
    "kahypar>=1.3.7",
    "optuna>=4.8.0",
]

[dependency-groups]
dev = [
    "ipykernel>=7.1.0",
    "jupyter",
    "pytest>=9.0.2",
]

[tool.pytest.ini_options]
markers = [
    "slow: realistic-scale tests; not run by default. Use `pytest -m slow`.",
]

[tool.hatch.build.targets.wheel]
packages = ["src"]

