"""SVHN backdoor — focused 1×N row: full-eval similarities + class-9 slice.

Strips the per-class 2×5 grid down to a single horizontal row of square
panels: the three full-eval similarity matrices that headline the main
figure (behavioural-test, behavioural-poison, tensor), followed by the
per-class slice for the backdoor target class 9. Same blueprint as
`svhn_backdoor.plot`: gentle terracotta↔slate palette, asymmetric
data-range bounds with `zmid=0`, manual axis-domain placement, no
title.

A fifth panel for *behavioural similarity restricted to class-9 inputs*
would round out the comparison (analogous to logan's `act_clean_2s`
control on class 2). That matrix is not in the cache — logan only
computed the class-2 control. Adding it requires re-running his
`similarity.py` with a class-9 mask, which needs the heavy
`checkpoints.pkl` (gitignored, regenerated by `train.py` in ~17s).
"""
import json

import plotly.graph_objects as go
import polars as pl

from src.figures.style import apply_style, save_figure
from src.figures.svhn_backdoor.prepare import CACHE

BG       = "#FAFAF7"
LABEL    = "#0f172a"
MUTED    = "#64748b"
BOUNDARY = "#0f172a"
TARGET_CLASS = 9
TARGET_COLOR = "#b91c1c"

HEAT_COLORSCALE = [
    [0.000, "#7c2d2d"],
    [0.150, "#a8453a"],
    [0.300, "#cf7f70"],
    [0.500, BG],
    [0.700, "#6b8ec0"],
    [0.850, "#33588f"],
    [1.000, "#1c3a72"],
]
BOUNDARY_KW = dict(line_color=BOUNDARY, line_width=3.0)

# Panel order: 3 full-eval similarities + class-9 slice. Each entry tells
# us which feather to read, what kind of pull (main vs slice), what to
# call the panel, and what color the title gets.
PANELS = (
    ("act_clean_full",    "main",  "Behavioural (test)",   LABEL),
    ("act_poisoned_full", "main",  "Behavioural (poison)", LABEL),
    ("tn_sim",            "main",  "Tensor",               LABEL),
    (TARGET_CLASS,        "slice", "class 9",              TARGET_COLOR),
)

# Layout: fig 1600 × 400, margin 4 → plot 1592 × 392. Each panel x_dom
# 0.235 → 374px wide; square requires y_dom 0.954 → 374px tall. Layout
# leaves ~0.025 above each panel for the title and ~0.011 of paper at
# the figure edges.
PANEL_X = ((0.000, 0.235), (0.255, 0.490), (0.510, 0.745), (0.765, 1.000))
PANEL_Y = (0.011, 0.965)


def _bounds(values):
    zmin = min(float(values.quantile(0.01)), -0.01)
    zmax = max(float(values.quantile(0.99)),  0.01)
    return zmin, zmax


def main():
    meta = json.loads((CACHE / "metadata.json").read_text(encoding="utf-8"))
    steps = meta["steps"]
    n = len(steps)
    step_to_idx = {s: i for i, s in enumerate(steps)}
    phases = meta["phases"]

    sim_long = pl.read_ipc(CACHE / "similarity.feather")
    slice_long = pl.read_ipc(CACHE / "slice_similarity.feather")

    def _matrix(metric):
        return (sim_long.filter(pl.col("metric") == metric)
                        .sort(["step_i", "step_j"])["value"]
                        .to_numpy().reshape(n, n).tolist())

    def _slice(class_idx):
        return (slice_long.filter(pl.col("class_idx") == class_idx)
                          .sort(["step_i", "step_j"])["value"]
                          .to_numpy().reshape(n, n).tolist())

    clean_last = step_to_idx[phases[0]["last_step"]]
    poison_first = step_to_idx[phases[1]["first_step"]]
    boundary = (clean_last + poison_first) / 2

    a_idx = list(range(clean_last + 1))
    b_idx = list(range(poison_first, n))

    def _gap(df, value_col="value"):
        df = df.with_columns(
            idx_i=pl.col("step_i").replace_strict(step_to_idx, return_dtype=pl.Int64),
            idx_j=pl.col("step_j").replace_strict(step_to_idx, return_dtype=pl.Int64),
        )
        within_b = df.filter(pl.col("idx_i").is_in(b_idx)
                             & pl.col("idx_j").is_in(b_idx)
                             & (pl.col("idx_i") != pl.col("idx_j")))[value_col].mean()
        across = df.filter(((pl.col("idx_i").is_in(a_idx) & pl.col("idx_j").is_in(b_idx))
                            | (pl.col("idx_i").is_in(b_idx) & pl.col("idx_j").is_in(a_idx))))[value_col].mean()
        return float(within_b) - float(across)

    indices = list(range(n))

    panels = []
    for spec in PANELS:
        key, kind, title, color = spec
        if kind == "main":
            df = sim_long.filter(pl.col("metric") == key)
            z = _matrix(key)
        else:
            df = slice_long.filter(pl.col("class_idx") == key)
            z = _slice(key)
        zmin, zmax = _bounds(df.filter(pl.col("step_i") != pl.col("step_j"))["value"])
        gap = _gap(df)
        panels.append((title, color, z, zmin, zmax, gap))

    fig = go.Figure()
    layout_axes = {}
    for k, ((title, color, z, zmin, zmax, gap), x_dom) in enumerate(zip(panels, PANEL_X), start=1):
        suffix = "" if k == 1 else str(k)
        x_id, y_id = f"x{suffix}", f"y{suffix}"
        fig.add_trace(go.Heatmap(z=z, x=indices, y=indices,
                                 zmin=zmin, zmax=zmax, zmid=0,
                                 colorscale=HEAT_COLORSCALE, showscale=False,
                                 xaxis=x_id, yaxis=y_id))
        layout_axes[f"xaxis{suffix}"] = dict(
            domain=list(x_dom), anchor=y_id, range=[-0.5, n - 0.5],
            showticklabels=False, ticks="",
            showline=False, zeroline=False, mirror=False, showgrid=False,
        )
        layout_axes[f"yaxis{suffix}"] = dict(
            domain=list(PANEL_Y), anchor=x_id, range=[-0.5, n - 0.5],
            showticklabels=False, ticks="",
            showline=False, zeroline=False, mirror=False, showgrid=False,
        )
        fig.add_shape(type="line", xref=f"x{suffix}", yref=f"y{suffix}",
                      x0=boundary, x1=boundary, y0=-0.5, y1=n - 0.5,
                      **BOUNDARY_KW)
        fig.add_shape(type="line", xref=f"x{suffix}", yref=f"y{suffix}",
                      x0=-0.5, x1=n - 0.5, y0=boundary, y1=boundary,
                      **BOUNDARY_KW)
        x_paper = (x_dom[0] + x_dom[1]) / 2
        text = (f"<b>{title}</b>"
                f"<span style='color:{MUTED}'>  ·  Δ = {gap:.2f}</span>")
        fig.add_annotation(x=x_paper, y=PANEL_Y[1] + 0.005, xref="paper", yref="paper",
                           text=text, showarrow=False,
                           xanchor="center", yanchor="bottom",
                           font=dict(size=15, color=color))

    apply_style(fig, title=None, width=1600, height=400, legend=False)
    fig.update_layout(
        layout_axes,
        margin=dict(l=4, r=4, t=4, b=4),
        paper_bgcolor=BG, plot_bgcolor=BG,
    )
    save_figure(fig, "svhn_backdoor_focused")
